### PR TITLE
[-] remove default public initializer for Actor w/ string

### LINKED ISSUE #45: Using an Actor with an arbitrary string as an Id causes a crash in automerge-swift
Example use case, encountered while I was cobbling up tests to verify the documentation work I'm doing:

```swift
func testCrashingExample() {
    struct Coordinate: Codable, Equatable {
        var x: Int?
    }

    // Initialize documents with known actor IDs.
    var doc1 = Document(Coordinate(), actor: Actor(actorId: "actor1"))
        
    // CRASHING HERE
    doc1.change { proxy in
        proxy.x.set(1)
    }
}
```

### PR DESCRIPTION
**Pull request by heckj**
Resolves #45

Adding constraint on Actor initialized with a string to match RSBackend conditions: that any strings be represented in hexadecimal characters ONLY. Set up with `precondition`, as we want to consider this a programming error if you've tried to initialize with another string representation.

Note: this only passes all unit tests when merged _after_ #49

### CODE REVIEW

File: Tests/AutomergeTest.swift [hunk 1]
```diff
@@ -7,7 +7,7 @@
 
 import Foundation
 import XCTest
-import Automerge
+@testable import Automerge
```
Comment (lightsprint09) [inline Tests/AutomergeTest.swift]: Is there a way to avoid using @testable

**Comment by lightsprint09** [comment]
Maybe we can just conform to ExpressibleByStringLiteral in the test target?

File: Tests/AutomergeTest.swift (hunk 1 above)
Comment (heckj) [reply Tests/AutomergeTest.swift]: Yeah - while we still have ExpressibleByStringLiteral, we can use that as the "hole" to creating arbitrary Actors by ActorID. Happy to update in that direction if you'd prefer.

**Comment by heckj** [comment]
Based on the detail from @ept in #48 - I think we do want to re-enable the actorID initializer akin to what we had, and simply make sure that it's always hex as opposed to allowing for an arbitrary string. Since that's probably more hassle to express in the type system - wanted to check what you thought about having a failable initializer here - either returning a nil actor when it fails - or expressing the failure as an exception being thrown (representing a programmer's error). I didn't see much in the way of either in the API so far, so I wasn't sure how you'd prefer to express this sort of thing.

**Comment by lightsprint09** [comment]
Might be a fatalError enough. Fail fast and early? Not sure if an optional init or throwing init helps to mitigate such errors

**Review by lightsprint09 — APPROVED** [review]
